defaults:
  - train: pr2l_hm3d_bc
  - data: pr2l_hm3d_objectnav_val
  - model: pr2l_prismatic_hm3d
  - objectives: pr2l_bc_hm3d
  - eval: default

config_name: habitat/pr2l_hm3d_bc_val
run_name: pr2l_hm3d_bc_val

data:
  episode_selection_manifest: episode_selections/pr2l_hm3d_objectnav/val_scene_object_balanced_7550.jsonl
  allow_missing_selected_episode_records: true
  balanced_subset_size: 7550

eval:
  episode_timeout_seconds: 30
